version: '3.9'

services:
  db:
    image: postgres:16
    container_name: pollapp-db
    environment:
      POSTGRES_DB: pollapp
      POSTGRES_USER: pollapp
      POSTGRES_PASSWORD: pollapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pollnet

  redis:
    image: redis:latest
    container_name: pollapp-redis
    ports:
      - "6379:6379"
    networks:
      - pollnet

  rabbitmq:
    image: rabbitmq:3-management
    container_name: pollapp-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - pollnet

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    container_name: pollapp-keycloak
    command: start-dev --hostname=keycloak  --hostname-strict=false
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/pollapp
      KC_DB_USERNAME: pollapp
      KC_DB_PASSWORD: pollapp
    ports:
      - "8082:8080"
    depends_on:
      - db
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - pollnet


  backend:
    build: ./backend
    container_name: pollapp-backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8081:8080"
    depends_on:
      - db
      - redis
      - rabbitmq
      - keycloak
    restart: always
    networks:
      - pollnet

  frontend:
    build: ./frontend
    container_name: pollapp-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_KEYCLOAK_URL=http://localhost:8082
      - VITE_KEYCLOAK_REALM=myrealm
      - VITE_KEYCLOAK_CLIENT_ID=myclient
      - VITE_API_URL=http://localhost:8081
    depends_on:
      - backend
    networks:
      - pollnet

volumes:
  postgres_data:
  keycloak_data:


networks:
  pollnet:
    driver: bridge
